// 招式名称中英文映射表
const moveNameMap = {
    // 普通技 - 基础动作
    'Standing Light Punch': '站立轻拳',
    'Standing Light Punch (Rapid Cancel)': '站立轻拳（快速取消）',
    'Standing Medium Punch': '站立中拳',
    'Standing Heavy Punch': '站立重拳',
    'Standing Heavy Punch (Charged)': '站立重拳（蓄力）',
    'Standing Light Kick': '站立轻脚',
    'Standing Medium Kick': '站立中脚',
    'Standing Heavy Kick': '站立重脚',
    'Crouching Light Punch': '蹲轻拳',
    'Crouching Light Punch (Rapid Cancel)': '蹲轻拳（快速取消）',
    'Crouching Medium Punch': '蹲中拳',
    'Crouching Heavy Punch': '蹲重拳',
    'Crouching Light Kick': '蹲轻脚',
    'Crouching Light Kick (Rapid Cancel)': '蹲轻脚（快速取消）',
    'Crouching Medium Kick': '蹲中脚',
    'Crouching Heavy Kick': '蹲重脚',
    'Jumping Light Punch': '跳轻拳',
    'Jumping Medium Punch': '跳中拳',
    'Jumping Heavy Punch': '跳重拳',
    'Jumping Heavy Punch (Charged)': '跳重拳（蓄力）',
    'Jumping Light Kick': '跳轻脚',
    'Jumping Medium Kick': '跳中脚',
    'Jumping Heavy Kick': '跳重脚',
    'Neutral Jumping Heavy Kick': '垂直跳重脚',
    'Jumping Heacy Punch (Charged)': '跳重拳（蓄力）',

    // 特殊技 (Command Normals)
    'Collarbone Breaker': '锁骨破坏者',
    'Solar Plexus Strike': '太阳神经丛打击',
    'Short Shoulder': '短肩撞',
    'Axe Kick': '斧踢',
    'High Blade Kick': '高踢',
    'Knee Bazooka': '膝盖火箭',
    'Jazz Hands': '爵士手',
    'Guile High Kick': '盖尔高踢',
    'Spinning Back Knuckle': '旋转后拳',
    'Double Impact': '双重冲击',
    'Phantom Slicer': '幻影切割',
    'Windmill Kick': '风车踢',
    'Water Curtain': '水帘',
    'Lightning Kick': '闪电踢',
    'Straight Punch': '直拳',
    'Swift Thrust': '快速刺击',
    'Diving Wyvern': '俯冲飞龙',
    'Hunting Falcon': '猎鹰',
    'Spiral Pirouette': '螺旋旋转',
    'Rapid Spin': '快速旋转',
    'Hell Attack': '地狱攻击',
    'Triangle Jump': '三角跳',
    'Wall Jump': '壁跳',
    'Dodge': '闪避',
    'Parry': '格挡',
    'Drive Impact': '驱动冲击',
    'Drive Parry': '驱动格挡',
    'Drive Reversal': '驱动反转',
    'Overdrive': '超速',

    // 桑吉尔夫 (Zangief) 普通技
    'Hellstab': '地狱刺',
    'Knee Hammer': '膝盖锤',
    'Headbutt': '头撞',
    'Cyclone Wheel Kick': '旋风轮踢',
    'Smetana Dropkick': '斯梅塔纳飞踢',
    'Flying Body Press': '飞行身体压制',
    'Flying Headbutt': '飞行头撞',
    'Machine Gun Chops (2)': '机枪劈（2段）',
    'Machine Gun Chops (3)': '机枪劈（3段）',
    'Power Stomps (1)': '强力踩踏（1段）',
    'Power Stomps (2)': '强力踩踏（2段）',
    'Power Stomps (3)': '强力踩踏（3段）',
    'Bodyslam': '身体压制',
    'Capture Suplex': '捕捉背摔',
    'German Suplex': '德式背摔',
    'Spinebuster': '脊椎破坏者',
    'Russian Drop': '俄式坠落',
    'Brainbuster': '脑部破坏者',

    // 桑吉尔夫 (Zangief) 必杀技
    'Double Lariat': '双重绑匪',
    'Double Lariat (OD)': '双重绑匪（EX）',
    'Borscht Dynamite': '罗宋炸药',
    'Borscht Dynamite (OD)': '罗宋炸药（EX）',
    'Russian Suplex': '俄式背摔',
    'Russian Suplex (OD)': '俄式背摔（EX）',
    'Siberian Express (Close Range)': '西伯利亚快车（近距离）',
    'Siberian Express (Close Range OD)': '西伯利亚快车（近距离EX）',
    'Siberian Express (Far Range)': '西伯利亚快车（远距离）',
    'Siberian Express (Far Range OD)': '西伯利亚快车（远距离EX）',
    'Screw Piledriver (Light)': '螺旋打桩机（轻）',
    'Screw Piledriver (Medium)': '螺旋打桩机（中）',
    'Screw Piledriver (Heavy)': '螺旋打桩机（重）',
    'Screw Piledriver (OD)': '螺旋打桩机（EX）',
    'Tundra Storm': '冻原风暴',
    'Cyclone Lariat (Charged)': '旋风绑匪（蓄力）',
    'Cyclone Lariat (Immediate)': '旋风绑匪（立即）',
    'Cyclone Lariat (Movement)': '旋风绑匪（移动）',

    // 桑吉尔夫 (Zangief) 超杀
    'Aerial Russian Slam': '空中俄式摔',
    'Bolshoi Storm Buster': '大剧院风暴破坏者',
    'Bolshoi Storm Buster (Critical Art)': '大剧院风暴破坏者（CA）',

    // 隆 (Ryu) 必杀技
    'Hadoken (Light)': '波动拳（轻）',
    'Hadoken (Medium)': '波动拳（中）',
    'Hadoken (Heavy)': '波动拳（重）',
    'Hadoken (OD)': '波动拳（EX）',
    'Shoryuken (Light)': '升龙拳（轻）',
    'Shoryuken (Medium)': '升龙拳（中）',
    'Shoryuken (Heavy)': '升龙拳（重）',
    'Shoryuken (OD)': '升龙拳（EX）',
    'Tatsumaki Zankukyaku (Light)': '龙卷旋风腿（轻）',
    'Tatsumaki Zankukyaku (Medium)': '龙卷旋风腿（中）',
    'Tatsumaki Zankukyaku (Heavy)': '龙卷旋风腿（重）',
    'Tatsumaki Zankukyaku (OD)': '龙卷旋风腿（EX）',
    'Jinrai Kick (Light)': '迅雷脚（轻）',
    'Jinrai Kick (Medium)': '迅雷脚（中）',
    'Jinrai Kick (Heavy)': '迅雷脚（重）',
    'Jinrai Kick (OD)': '迅雷脚（EX）',
    'Hashogeki': '波掌击',
    'Hashogeki (OD)': '波掌击（EX）',
    'Denjin Charge': '电刃蓄力',

    // 隆 (Ryu) 超杀
    'Shinku Hadoken': '真空波动拳',
    'Shin Shoryuken': '真升龙拳',
    'Denjin Hadoken': '电刃波动拳',

    // 肯 (Ken) 必杀技
    'Shoryuken (Light) Reppa': '升龙拳（轻）',
    'Shoryuken (Medium) Reppa': '升龙拳（中）',
    'Shoryuken (Heavy) Reppa': '升龙拳（重）',
    'Shoryuken (OD) Reppa': '升龙拳（EX）',
    'Dragonlash Kick (Light)': '龙闪脚（轻）',
    'Dragonlash Kick (Medium)': '龙闪脚（中）',
    'Dragonlash Kick (Heavy)': '龙闪脚（重）',
    'Dragonlash Kick (OD)': '龙闪脚（EX）',
    'Kazekama Shinrai (Light)': '风神脚（轻）',
    'Kazekama Shinrai (Medium)': '风神脚（中）',
    'Kazekama Shinrai (Heavy)': '风神脚（重）',
    'Kazekama Shinrai (OD)': '风神脚（EX）',

    // 肯 (Ken) 超杀
    'Shippu Jinraikyaku': '疾风迅雷脚',
    'Shinryu Reppa': '神龙烈破',

    // 朱莉 (Juri) 必杀技
    'Fuhajin (Light)': '风破刃（轻）',
    'Fuhajin (Medium)': '风破刃（中）',
    'Fuhajin (Heavy)': '风破刃（重）',
    'Fuhajin (OD)': '风破刃（EX）',
    'Ankensatsu': '暗剑杀',
    'Ankensatsu (OD)': '暗剑杀（EX）',
    'Go Ohsatsu': '五黄杀',
    'Go Ohsatsu (OD)': '五黄杀（EX）',
    'Shikusen': '紫电脚',
    'Shikusen (OD)': '紫电脚（EX）',
    'Feng Shui Engine': '风水引擎',

    // 朱莉 (Juri) 超杀
    'Sakkai Fuhazan': '开花风破斩',
    'Kaisen Dankai Raku': '开战断崖落',

    // A.K.I. 必杀技
    'Nightshade Pulse': '夜影脉冲',
    'Nightshade Pulse (OD)': '夜影脉冲（EX）',
    'Orchid Spring': '兰花之泉',
    'Toxic Wreath': '毒冠',
    'Serpent Lash (Light)': '蛇鞭（轻）',
    'Serpent Lash (Medium)': '蛇鞭（中）',
    'Serpent Lash (Heavy)': '蛇鞭（重）',
    'Serpent Lash (OD)': '蛇鞭（EX）',
    'Cruel Fate (Light)': '残酷命运（轻）',
    'Cruel Fate (Medium)': '残酷命运（中）',
    'Cruel Fate (Heavy)': '残酷命运（重）',
    'Cruel Fate (OD)': '残酷命运（EX）',
    'Snake Step (Light)': '蛇步（轻）',
    'Snake Step (Medium)': '蛇步（中）',
    'Snake Step (Heavy)': '蛇步（重）',
    'Snake Step (OD)': '蛇步（EX）',
    'Sinister Slide': '邪恶滑行',

    // A.K.I. 超杀
    'Deadly Implication': '致命牵连',

    // 豪鬼 (Akuma) 必杀技
    'Gou Hadoken (Light)': '豪波动拳（轻）',
    'Gou Hadoken (Medium)': '豪波动拳（中）',
    'Gou Hadoken (Heavy)': '豪波动拳（重）',
    'Gou Hadoken (OD)': '豪波动拳（EX）',
    'Gou Hadoken (Light) (Charge Level 2)': '豪波动拳（轻）蓄力2',
    'Gou Hadoken (Light) (Charge Level 3)': '豪波动拳（轻）蓄力3',
    'Gou Hadoken (Medium) (Charge Level 2)': '豪波动拳（中）蓄力2',
    'Gou Hadoken (Medium) (Charge Level 3)': '豪波动拳（中）蓄力3',
    'Gou Hadoken (Heavy) (Charge Level 2)': '豪波动拳（重）蓄力2',
    'Gou Hadoken (Heavy) (Charge Level 3)': '豪波动拳（重）蓄力3',
    'Gou Hadoken (Charged) (OD)': '豪波动拳（蓄力EX）',
    'Zanku Hadoken': '斩空波动拳',
    'Zanku Hadoken (OD)': '斩空波动拳（EX）',
    'Gou Shoryuken (Light)': '豪升龙拳（轻）',
    'Gou Shoryuken (Medium)': '豪升龙拳（中）',
    'Gou Shoryuken (Heavy)': '豪升龙拳（重）',
    'Gou Shoryuken (OD)': '豪升龙拳（EX）',
    'Tatsumaki Zankukyaku (Light)': '龙卷斩空脚（轻）',
    'Tatsumaki Zankukyaku (Medium)': '龙卷斩空脚（中）',
    'Tatsumaki Zankukyaku (Heavy)': '龙卷斩空脚（重）',
    'Tatsumaki Zankukyaku (OD)': '龙卷斩空脚（EX）',
    'Aerial Tatsumaki Zankukyaku': '空中龙卷斩空脚',
    'Aerial Tatsumaki Zankukyaku (OD)': '空中龙卷斩空脚（EX）',
    'Adamant Flame (Light 1)': '金刚焰（轻）1',
    'Adamant Flame (Light 2)': '金刚焰（轻）2',
    'Adamant Flame (Medium 1)': '金刚焰（中）1',
    'Adamant Flame (Medium 2)': '金刚焰（中）2',
    'Adamant Flame (Heavy 1)': '金刚焰（重）1',
    'Adamant Flame (Heavy 2)': '金刚焰（重）2',
    'Adamant Flame (OD 1)': '金刚焰（EX）1',
    'Adamant Flame (OD 2)': '金刚焰（EX）2',
    'Demon Raid': '恶魔袭击',
    'Demon Raid (OD)': '恶魔袭击（EX）',
    'Ashura Senku': '阿修罗闪空',

    // 豪鬼 (Akuma) 超杀
    'Messatsu Gou Hadou': '灭豪波动',
    'Tenma Gou Zanku': '天魔豪斩空',
    'Messatsu Gou Shoryu': '灭豪升龙',
    'Kongou Kokuretsu Zan': '金刚国裂斩',

    // 布兰卡 (Blanka) 必杀技
    'Electric Thunder (Light)': '雷电（轻）',
    'Electric Thunder (Medium)': '雷电（中）',
    'Electric Thunder (Heavy)': '雷电（重）',
    'Electric Thunder (OD)': '雷电（EX）',
    'Rolling Attack (Light)': '滚动攻击（轻）',
    'Rolling Attack (Medium)': '滚动攻击（中）',
    'Rolling Attack (Heavy)': '滚动攻击（重）',
    'Rolling Attack (OD)': '滚动攻击（EX）',
    'Backstep Rolling (Light)': '后滚（轻）',
    'Backstep Rolling (Medium)': '后滚（中）',
    'Backstep Rolling (Heavy)': '后滚（重）',
    'Backstep Rolling (OD)': '后滚（EX）',
    'Vertical Rolling (Light)': '垂直滚动（轻）',
    'Vertical Rolling (Medium)': '垂直滚动（中）',
    'Vertical Rolling (Heavy)': '垂直滚动（重）',
    'Vertical Rolling (OD)': '垂直滚动（EX）',
    'Wild Hunt': '野性狩猎',

    // 布兰卡 (Blanka) 超杀
    'Shout of Earth': '大地之吼',
    'Ground Shave Rolling': '地面剃须滚动',

    // 嘉米 (Cammy) 必杀技
    'Spiral Arrow (Light)': '螺旋箭（轻）',
    'Spiral Arrow (Medium)': '螺旋箭（中）',
    'Spiral Arrow (Heavy)': '螺旋箭（重）',
    'Spiral Arrow (OD)': '螺旋箭（EX）',
    'Cannon Spike (Light)': '加农刺（轻）',
    'Cannon Spike (Medium)': '加农刺（中）',
    'Cannon Spike (Heavy)': '加农刺（重）',
    'Cannon Spike (OD)': '加农刺（EX）',
    'Quick Spin Knuckle (Light)': '快速旋转拳（轻）',
    'Quick Spin Knuckle (Medium)': '快速旋转拳（中）',
    'Quick Spin Knuckle (Heavy)': '快速旋转拳（重）',
    'Quick Spin Knuckle (OD)': '快速旋转拳（EX）',
    'Hooligan Combination (Light)': '流氓组合（轻）',
    'Hooligan Combination (Medium)': '流氓组合（中）',
    'Hooligan Combination (Heavy)': '流氓组合（重）',
    'Hooligan Combination (OD)': '流氓组合（EX）',
    'Killer Bee Spin': '杀人蜂旋转',

    // 嘉米 (Cammy) 超杀
    'Spin Drive Smasher': '旋转驱动粉碎',
    'Delta Red Assault': '德尔塔红攻击',

    // 春丽 (Chun-Li) 必杀技
    'Kikoken (Light)': '气功拳（轻）',
    'Kikoken (Medium)': '气功拳（中）',
    'Kikoken (Heavy)': '气功拳（重）',
    'Kikoken (OD)': '气功拳（EX）',
    'Hyakuretsukyaku (Light)': '百裂脚（轻）',
    'Hyakuretsukyaku (Medium)': '百裂脚（中）',
    'Hyakuretsukyaku (Heavy)': '百裂脚（重）',
    'Hyakuretsukyaku (OD)': '百裂脚（EX）',
    'Spinning Bird Kick (Light)': '回旋鹤脚蹴（轻）',
    'Spinning Bird Kick (Medium)': '回旋鹤脚蹴（中）',
    'Spinning Bird Kick (Heavy)': '回旋鹤脚蹴（重）',
    'Spinning Bird Kick (OD)': '回旋鹤脚蹴（EX）',
    'Tensho Kicks (Light)': '天升脚（轻）',
    'Tensho Kicks (Medium)': '天升脚（中）',
    'Tensho Kicks (Heavy)': '天升脚（重）',
    'Tensho Kicks (OD)': '天升脚（EX）',

    // 春丽 (Chun-Li) 超杀
    'Soten Ranka': '双天乱華',
    'Kikosho': '气功掌',

    // 迪杰 (Dee Jay) 必杀技
    'Air Slasher (Light)': '空中斩（轻）',
    'Air Slasher (Medium)': '空中斩（中）',
    'Air Slasher (Heavy)': '空中斩（重）',
    'Air Slasher (OD)': '空中斩（EX）',
    'Jackknife Maximum (Light)': '杰克刀最大（轻）',
    'Jackknife Maximum (Medium)': '杰克刀最大（中）',
    'Jackknife Maximum (Heavy)': '杰克刀最大（重）',
    'Jackknife Maximum (OD)': '杰克刀最大（EX）',
    'Rolling Sobat (Light)': '滚动扫腿（轻）',
    'Rolling Sobat (Medium)': '滚动扫腿（中）',
    'Rolling Sobat (Heavy)': '滚动扫腿（重）',
    'Rolling Sobat (OD)': '滚动扫腿（EX）',
    'Machine Gun Upper (Light)': '机枪上勾拳（轻）',
    'Machine Gun Upper (Medium)': '机枪上勾拳（中）',
    'Machine Gun Upper (Heavy)': '机枪上勾拳（重）',
    'Machine Gun Upper (OD)': '机枪上勾拳（EX）',
    'Jus Cool': '就是酷',

    // 迪杰 (Dee Jay) 超杀
    'Maximum Strike': '最大打击',
    'Sobat Festival': '扫腿节',

    // 达尔锡 (Dhalsim) 必杀技
    'Yoga Fire (Light)': '瑜伽火（轻）',
    'Yoga Fire (Medium)': '瑜伽火（中）',
    'Yoga Fire (Heavy)': '瑜伽火（重）',
    'Yoga Fire (OD)': '瑜伽火（EX）',
    'Yoga Flame (Light)': '瑜伽烈焰（轻）',
    'Yoga Flame (Medium)': '瑜伽烈焰（中）',
    'Yoga Flame (Heavy)': '瑜伽烈焰（重）',
    'Yoga Flame (OD)': '瑜伽烈焰（EX）',
    'Yoga Arch (Light)': '瑜伽弓（轻）',
    'Yoga Arch (Medium)': '瑜伽弓（中）',
    'Yoga Arch (Heavy)': '瑜伽弓（重）',
    'Yoga Arch (OD)': '瑜伽弓（EX）',
    'Yoga Blast (Light)': '瑜伽爆破（轻）',
    'Yoga Blast (Medium)': '瑜伽爆破（中）',
    'Yoga Blast (Heavy)': '瑜伽爆破（重）',
    'Yoga Blast (OD)': '瑜伽爆破（EX）',
    'Yoga Teleport': '瑜伽传送',

    // 达尔锡 (Dhalsim) 超杀
    'Yoga Inferno': '瑜伽地狱',
    'Yoga Sunburst': '瑜伽日出',

    // 艾德 (Ed) 必杀技
    'Psycho Spark (Light)': '念气火花（轻）',
    'Psycho Spark (Medium)': '念气火花（中）',
    'Psycho Spark (Heavy)': '念气火花（重）',
    'Psycho Spark (OD)': '念气火花（EX）',
    'Psycho Upper (Light)': '念气上勾拳（轻）',
    'Psycho Upper (Medium)': '念气上勾拳（中）',
    'Psycho Upper (Heavy)': '念气上勾拳（重）',
    'Psycho Upper (OD)': '念气上勾拳（EX）',
    'Psycho Flick (Light)': '念气弹（轻）',
    'Psycho Flick (Medium)': '念气弹（中）',
    'Psycho Flick (Heavy)': '念气弹（重）',
    'Psycho Flick (OD)': '念气弹（EX）',
    'Psycho Shoot (Light)': '念气射击（轻）',
    'Psycho Shoot (Medium)': '念气射击（中）',
    'Psycho Shoot (Heavy)': '念气射击（重）',
    'Psycho Shoot (OD)': '念气射击（EX）',
    'Psycho Snatcher (Light)': '念气捕手（轻）',
    'Psycho Snatcher (Medium)': '念气捕手（中）',
    'Psycho Snatcher (Heavy)': '念气捕手（重）',
    'Psycho Snatcher (OD)': '念气捕手（EX）',

    // 艾德 (Ed) 超杀
    'Psycho Blitz': '念气闪电',
    'Psycho Storm': '念气风暴',
    'Psycho Cannon': '念气加农',

    // 本田 (E. Honda) 必杀技
    'Hundred Hand Slap (Light)': '百裂掌（轻）',
    'Hundred Hand Slap (Medium)': '百裂掌（中）',
    'Hundred Hand Slap (Heavy)': '百裂掌（重）',
    'Hundred Hand Slap (OD)': '百裂掌（EX）',
    'Sumo Headbutt (Light)': '相扑头撞（轻）',
    'Sumo Headbutt (Medium)': '相扑头撞（中）',
    'Sumo Headbutt (Heavy)': '相扑头撞（重）',
    'Sumo Headbutt (OD)': '相扑头撞（EX）',
    'Sumo Smash (Light)': '相扑压（轻）',
    'Sumo Smash (Medium)': '相扑压（中）',
    'Sumo Smash (Heavy)': '相扑压（重）',
    'Sumo Smash (OD)': '相扑压（EX）',
    'Oicho Throw': '大外投',
    'Sumo Rush': '相扑突击',

    // 本田 (E. Honda) 超杀
    'Ultimate Killer Headbutt': '终极杀手头撞',
    'Fuji Oroshi': '富士落',

    // 盖尔 (Guile) 必杀技
    'Sonic Boom (Light)': '音速爆（轻）',
    'Sonic Boom (Medium)': '音速爆（中）',
    'Sonic Boom (Heavy)': '音速爆（重）',
    'Sonic Boom (OD)': '音速爆（EX）',
    'Flash Kick (Light)': '闪光踢（轻）',
    'Flash Kick (Medium)': '闪光踢（中）',
    'Flash Kick (Heavy)': '闪光踢（重）',
    'Flash Kick (OD)': '闪光踢（EX）',
    'Sonic Blade (Light)': '音速刃（轻）',
    'Sonic Blade (Medium)': '音速刃（中）',
    'Sonic Blade (Heavy)': '音速刃（重）',
    'Sonic Blade (OD)': '音速刃（EX）',
    'Solid Puncher': '坚固拳击手',

    // 盖尔 (Guile) 超杀
    'Sonic Hurricane': '音速飓风',
    'Crossfire Somersault': '交叉火力空翻',

    // 杰米 (Jamie) 必杀技
    'Freeflow Strikes (Light)': '自由流打击（轻）',
    'Freeflow Strikes (Medium)': '自由流打击（中）',
    'Freeflow Strikes (Heavy)': '自由流打击（重）',
    'Freeflow Strikes (OD)': '自由流打击（EX）',
    'Swagger Step (Light)': ' swagger步（轻）',
    'Swagger Step (Medium)': ' swagger步（中）',
    'Swagger Step (Heavy)': ' swagger步（重）',
    'Swagger Step (OD)': ' swagger步（EX）',
    'Arrow Kick (Light)': '箭踢（轻）',
    'Arrow Kick (Medium)': '箭踢（中）',
    'Arrow Kick (Heavy)': '箭踢（重）',
    'Arrow Kick (OD)': '箭踢（EX）',
    'Luminous Dance': '发光舞蹈',
    'Divekick': '俯冲踢',
    'Bakkai': '爆快',
    'Tensei Kick': '天升踢',
    'The Devil Inside': '内心的恶魔',

    // 杰米 (Jamie) 超杀
    'Getsuga Saiho': '月牙赛宝',
    'Kau Kau Siguru': '考考西古鲁',

    // JP 必杀技
    'Triglav (Light)': '特里格拉夫（轻）',
    'Triglav (Medium)': '特里格拉夫（中）',
    'Triglav (Heavy)': '特里格拉夫（重）',
    'Triglav (OD)': '特里格拉夫（EX）',
    'Stribog (Light)': '斯特里博格（轻）',
    'Stribog (Medium)': '斯特里博格（中）',
    'Stribog (Heavy)': '斯特里博格（重）',
    'Stribog (OD)': '斯特里博格（EX）',
    'Amnesia': '失忆',
    'Departure (Light)': '离去（轻）',
    'Departure (Medium)': '离去（中）',
    'Departure (Heavy)': '离去（重）',
    'Departure (OD)': '离去（EX）',
    'Torbalan (Light)': '托巴兰（轻）',
    'Torbalan (Medium)': '托巴兰（中）',
    'Torbalan (Heavy)': '托巴兰（重）',
    'Torbalan (OD)': '托巴兰（EX）',

    // JP 超杀
    'Chornobog': '切尔诺伯格',
    'Interdiction': '禁令',

    // 金伯莉 (Kimberly) 必杀技
    'Bushin Senpukyaku (Light)': '武神旋风脚（轻）',
    'Bushin Senpukyaku (Medium)': '武神旋风脚（中）',
    'Bushin Senpukyaku (Heavy)': '武神旋风脚（重）',
    'Bushin Senpukyaku (OD)': '武神旋风脚（EX）',
    'Sprint (Light)': '冲刺（轻）',
    'Sprint (Medium)': '冲刺（中）',
    'Sprint (Heavy)': '冲刺（重）',
    'Sprint (OD)': '冲刺（EX）',
    'Vagabond Edge (Light)': '流浪者之刃（轻）',
    'Vagabond Edge (Medium)': '流浪者之刃（中）',
    'Vagabond Edge (Heavy)': '流浪者之刃（重）',
    'Vagabond Edge (OD)': '流浪者之刃（EX）',
    'Genius at Play': '天才游戏',

    // 金伯莉 (Kimberly) 超杀
    'Bushin Beats': '武神节拍',
    'Nue Twister': '鵺扭转',

    // 莉莉 (Lily) 必杀技
    'Condor Wind (Light)': '秃鹰之风（轻）',
    'Condor Wind (Medium)': '秃鹰之风（中）',
    'Condor Wind (Heavy)': '秃鹰之风（重）',
    'Condor Wind (OD)': '秃鹰之风（EX）',
    'Condor Spire (Light)': '秃鹰螺旋（轻）',
    'Condor Spire (Medium)': '秃鹰螺旋（中）',
    'Condor Spire (Heavy)': '秃鹰螺旋（重）',
    'Condor Spire (OD)': '秃鹰螺旋（EX）',
    'Condor Dive (Light)': '秃鹰俯冲（轻）',
    'Condor Dive (Medium)': '秃鹰俯冲（中）',
    'Condor Dive (Heavy)': '秃鹰俯冲（重）',
    'Condor Dive (OD)': '秃鹰俯冲（EX）',
    'Tomahawk Buster (Light)': '战斧破碎机（轻）',
    'Tomahawk Buster (Medium)': '战斧破碎机（中）',
    'Tomahawk Buster (Heavy)': '战斧破碎机（重）',
    'Tomahawk Buster (OD)': '战斧破碎机（EX）',

    // 莉莉 (Lily) 超杀
    'Thunderbird': '雷鸟',
    'Raging Typhoon': '狂暴台风',

    // 卢克 (Luke) 必杀技
    'Sand Blast (Light)': '沙爆（轻）',
    'Sand Blast (Medium)': '沙爆（中）',
    'Sand Blast (Heavy)': '沙爆（重）',
    'Sand Blast (OD)': '沙爆（EX）',
    'Flash Knuckle (Light)': '闪光拳（轻）',
    'Flash Knuckle (Medium)': '闪光拳（中）',
    'Flash Knuckle (Heavy)': '闪光拳（重）',
    'Flash Knuckle (OD)': '闪光拳（EX）',
    'Rising Uppercut (Light)': '上升上勾拳（轻）',
    'Rising Uppercut (Medium)': '上升上勾拳（中）',
    'Rising Uppercut (Heavy)': '上升上勾拳（重）',
    'Rising Uppercut (OD)': '上升上勾拳（EX）',
    'Aerial Flash Knuckle': '空中闪光拳',
    'Aerial Flash Knuckle (OD)': '空中闪光拳（EX）',

    // 卢克 (Luke) 超杀
    'Vulcan Blast': '火神爆破',
    'Eraser': '橡皮擦',
    'Pale Rider': '苍白骑士',

    // 舞 (Mai) 必杀技
    'Kachousen (Light)': '花蝶扇（轻）',
    'Kachousen (Medium)': '花蝶扇（中）',
    'Kachousen (Heavy)': '花蝶扇（重）',
    'Kachousen (OD)': '花蝶扇（EX）',
    'Ryuuenbu (Light)': '龙炎舞（轻）',
    'Ryuuenbu (Medium)': '龙炎舞（中）',
    'Ryuuenbu (Heavy)': '龙炎舞（重）',
    'Ryuuenbu (OD)': '龙炎舞（EX）',
    'Hishou Ryuuenjin (Light)': '飞龙炎阵（轻）',
    'Hishou Ryuuenjin (Medium)': '飞龙炎阵（中）',
    'Hishou Ryuuenjin (Heavy)': '飞龙炎阵（重）',
    'Hishou Ryuuenjin (OD)': '飞龙炎阵（EX）',
    'Musasabi no Mai (Light)': '鵺之舞（轻）',
    'Musasabi no Mai (Medium)': '鵺之舞（中）',
    'Musasabi no Mai (Heavy)': '鵺之舞（重）',
    'Musasabi no Mai (OD)': '鵺之舞（EX）',
    'Suiryuu Setsu': '水流切',
    'Kuuchuu Kachousen': '空中花蝶扇',

    // 舞 (Mai) 超杀
    'Chou Hissatsu Shinobi Bachi': '超必杀忍蜂',
    'Gekka Choujin': '月华蝶刃',

    // 玛农 (Manon) 必杀技
    'Manege Dore (Light)': '马内吉·多尔（轻）',
    'Manege Dore (Medium)': '马内吉·多尔（中）',
    'Manege Dore (Heavy)': '马内吉·多尔（重）',
    'Manege Dore (OD)': '马内吉·多尔（EX）',
    'Rond-point (Light)': '隆德安（轻）',
    'Rond-point (Medium)': '隆德安（中）',
    'Rond-point (Heavy)': '隆德安（重）',
    'Rond-point (OD)': '隆德安（EX）',
    'Degage (Light)': '德加吉（轻）',
    'Degage (Medium)': '德加吉（中）',
    'Degage (Heavy)': '德加吉（重）',
    'Degage (OD)': '德加吉（EX）',

    // 玛农 (Manon) 超杀
    'A Grand Jeté': '大跳跃',
    'Renversé': '翻转',
    'Pas de Deux': '双人舞',

    // 玛丽莎 (Marisa) 必杀技
    'Gladius (Light)': '格拉迪乌斯（轻）',
    'Gladius (Medium)': '格拉迪乌斯（中）',
    'Gladius (Heavy)': '格拉迪乌斯（重）',
    'Gladius (OD)': '格拉迪乌斯（EX）',
    'Dimachaerus (Light)': '迪马凯鲁斯（轻）',
    'Dimachaerus (Medium)': '迪马凯鲁斯（中）',
    'Dimachaerus (Heavy)': '迪马凯鲁斯（重）',
    'Dimachaerus (OD)': '迪马凯鲁斯（EX）',
    'Phalanx (Light)': '方阵（轻）',
    'Phalanx (Medium)': '方阵（中）',
    'Phalanx (Heavy)': '方阵（重）',
    'Phalanx (OD)': '方阵（EX）',
    'Scutum (Light)': '斯库图姆（轻）',
    'Scutum (Medium)': '斯库图姆（中）',
    'Scutum (Heavy)': '斯库图姆（重）',
    'Scutum (OD)': '斯库图姆（EX）',

    // 玛丽莎 (Marisa) 超杀
    'Javelin of Marisa': '玛丽莎之矛',
    'Meteor Combo': '流星连击',
    'Ultimate Marisa': '终极玛丽莎',

    // 维加 (M. Bison) 必杀技
    'Psycho Blast (Light)': '念气爆破（轻）',
    'Psycho Blast (Medium)': '念气爆破（中）',
    'Psycho Blast (Heavy)': '念气爆破（重）',
    'Psycho Blast (OD)': '念气爆破（EX）',
    'Psycho Mine (Light)': '念气地雷（轻）',
    'Psycho Mine (Medium)': '念气地雷（中）',
    'Psycho Mine (Heavy)': '念气地雷（重）',
    'Psycho Mine (OD)': '念气地雷（EX）',
    'Double Knee Press (Light)': '双膝压（轻）',
    'Double Knee Press (Medium)': '双膝压（中）',
    'Double Knee Press (Heavy)': '双膝压（重）',
    'Double Knee Press (OD)': '双膝压（EX）',
    'Head Press (Light)': '头压（轻）',
    'Head Press (Medium)': '头压（中）',
    'Head Press (Heavy)': '头压（重）',
    'Head Press (OD)': '头压（EX）',
    'Devil Reverse (Light)': '恶魔反转（轻）',
    'Devil Reverse (Medium)': '恶魔反转（中）',
    'Devil Reverse (Heavy)': '恶魔反转（重）',
    'Devil Reverse (OD)': '恶魔反转（EX）',
    'Shadow Rise': '影升',

    // 维加 (M. Bison) 超杀
    'Psycho Crusher': '念气粉碎',
    'Knee Press Nightmare': '膝压噩梦',
    'Ultimate Psycho Crusher': '终极念气粉碎',

    // 拉希德 (Rashid) 必杀技
    'Spinning Mixer (Light)': '旋转混合器（轻）',
    'Spinning Mixer (Medium)': '旋转混合器（中）',
    'Spinning Mixer (Heavy)': '旋转混合器（重）',
    'Spinning Mixer (OD)': '旋转混合器（EX）',
    'Eagle Spike (Light)': '鹰刺（轻）',
    'Eagle Spike (Medium)': '鹰刺（中）',
    'Eagle Spike (Heavy)': '鹰刺（重）',
    'Eagle Spike (OD)': '鹰刺（EX）',
    'Whirlwind Shot (Light)': '旋风射击（轻）',
    'Whirlwind Shot (Medium)': '旋风射击（中）',
    'Whirlwind Shot (Heavy)': '旋风射击（重）',
    'Whirlwind Shot (OD)': '旋风射击（EX）',
    'Nasher Slide (Light)': '纳舍尔滑行（轻）',
    'Nasher Slide (Medium)': '纳舍尔滑行（中）',
    'Nasher Slide (Heavy)': '纳舍尔滑行（重）',
    'Nasher Slide (OD)': '纳舍尔滑行（EX）',
    'Wind Current': '风流',

    // 拉希德 (Rashid) 超杀
    'Ysaar': '亚萨尔',
    'Altair': '阿尔泰尔',
    'Super Rashid Kick': '超级拉希德踢',

    // 特瑞 (Terry) 必杀技
    'Power Wave (Light)': '能量波（轻）',
    'Power Wave (Medium)': '能量波（中）',
    'Power Wave (Heavy)': '能量波（重）',
    'Power Wave (OD)': '能量波（EX）',
    'Burning Knuckle (Light)': '燃烧拳（轻）',
    'Burning Knuckle (Medium)': '燃烧拳（中）',
    'Burning Knuckle (Heavy)': '燃烧拳（重）',
    'Burning Knuckle (OD)': '燃烧拳（EX）',
    'Crack Shoot (Light)': '裂痕射击（轻）',
    'Crack Shoot (Medium)': '裂痕射击（中）',
    'Crack Shoot (Heavy)': '裂痕射击（重）',
    'Crack Shoot (OD)': '裂痕射击（EX）',
    'Power Dunk (Light)': '能量扣篮（轻）',
    'Power Dunk (Medium)': '能量扣篮（中）',
    'Power Dunk (Heavy)': '能量扣篮（重）',
    'Power Dunk (OD)': '能量扣篮（EX）',
    'Rising Tackle': '上升攻击',

    // 特瑞 (Terry) 超杀
    'Power Geyser': '能量间歇泉',
    'Buster Wolf': '破坏狼',
};

// 智能翻译函数
function getMoveNameCN(name) {
    // 先查精确匹配
    if (moveNameMap[name]) {
        return moveNameMap[name];
    }

    // 尝试规则化翻译
    let result = name;

    // 基础动作翻译
    const basicMap = {
        'Standing': '站立',
        'Crouching': '蹲',
        'Jumping': '跳',
        'Neutral Jumping': '垂直跳',
        'Light': '轻',
        'Medium': '中',
        'Heavy': '重',
        'Punch': '拳',
        'Kick': '脚',
        'OD': 'EX',
        '(OD)': '（EX）',
        '(Light)': '（轻）',
        '(Medium)': '（中）',
        '(Heavy)': '（重）',
        '(Charge Level 2)': '蓄力2',
        '(Charge Level 3)': '蓄力3',
        '(Charged)': '（蓄力）',
        '(Rapid Cancel)': '（快速取消）',
    };

    for (const [en, cn] of Object.entries(basicMap)) {
        result = result.replace(new RegExp(en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), cn);
    }

    return result;
}

// 导出
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { moveNameMap, getMoveNameCN };
}
